plugin:
    name: 'pensoft.mailing::lang.plugin.name'
    description: 'pensoft.mailing::lang.plugin.description'
    author: Pensoft
    icon: icon-envelope
    homepage: ''
navigation:
    groups:
        label: Mailing
        url: pensoft/mailing/groups
        icon: icon-envelope
        sideMenu:
            groups:
                label: Groups
                url: pensoft/mailing/groups
                icon: icon-group
            mails:
                label: Mails
                url: pensoft/mailing/mails
                icon: icon-envelope-o
